- id: 200
  key: satoshi
  currency: btc
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 400
  key: bank
  currency: eur
  sort_order: 2
  bank_accounts:
    -
      bank: 'Your Bank Name'
      branch: 'Your Bank Branch'
      holder: 'Your Account Holder'
      account: 'Your Account Number'
- id: 600
  key: ether
  currency: eth
  min_confirm: 1
  max_confirm: 6
- id: 800
  key: dollar
  currency: usd 
  sort_order: 2
  bank_accounts:
    -
      bank: 'Your Bank Name'
      branch: 'Your Bank Branch'
      holder: 'Your Account Holder'
      account: 'Your Account Number'
- id: 1000
  key: pound
  currency: gbp 
  sort_order: 2
  bank_accounts:
    -
      bank: 'Your Bank Name'
      branch: 'Your Bank Branch'
      holder: 'Your Account Holder'
      account: 'Your Account Number'
- id: 1100
  key: bitcoincash
  currency: bch
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1200
  key: bitcoingold
  currency: btg
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1300
  key: ripple
  currency: xrp
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1400
  key: litecoin
  currency: ltc
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
