- id: 200
  key: satoshi
  currency: btc
  fixed: 8
  fee: 0.1
  fee_type: percentage
  inuse: true
  type: WithdrawChannelSatoshi
- id: 400
  key: bank
  currency: eur
  fixed: 2
  min: 15
  max: 50000
  fee: 1
  fee_type: percentage
  proportion: true
  inuse: true
  type: WithdrawChannelBank
- id: 500
  key: ether
  currency: eth
  min_confirm: 1
  max_confirm: 6
  inuse: true
  fixed: 8
  fee: 0.1
  fee_type: percentage
  type: WithdrawChannelEthereum
- id: 600
  key: dollar
  currency: usd
  fixed: 2
  min: 15
  max: 50000
  fee: 1
  fee_type: percentage
  proportion: true
  inuse: true
  type: WithdrawChannelDollar 
- id: 700
  key: pound
  currency: gbp
  fixed: 2
  fee_max: 0.1
  min: 15
  max: 50000
  fee: 1
  fee_type: percentage
  proportion: true
  inuse: true
  type: WithdrawChannelPound 
- id: 800
  key: bitcoincash
  currency: bch
  fixed: 8
  fee: 0.1
  fee_type: percentage
  inuse: true
  type: WithdrawChannelBitcoincash
- id: 900
  key: bitcoingold
  currency: btg
  fixed: 8
  fee: 0.1
  fee_type: percentage
  inuse: true
  type: WithdrawChannelBitcoingold
- id: 1000
  key: ripple
  currency: xrp
  fixed: 8
  fee: 0.1
  fee_type: percentage
  inuse: true
  type: WithdrawChannelRipple
- id: 1100
  key: litecoin
  currency: ltc
  fixed: 8
  fee: 0.1
  fee_type: percentage
  inuse: true
  type: WithdrawChannelLitecoin
